Feature/#84 내 여행 홈 / 계획 페이지 업데이트 및 기능 연결
F-orever/gabozago_FE pull request #93
Opened 2024-05-15 07:43 UTC by SugarSyrup

### 작업한 내용
관련 이슈: #84
- 내 여행 탭, UI 기능 구현
- 내 여행 계획 및 틀 생성을 위한 UI 기능 구현

### 중점적으로 봐 주었으면 하는 부분
- rebase를 했는데 commit이 왜 저따구로 흘러가지?? ( 일단 #84 위주로 보시면 될 것 같습니당 )
- baseURL이 놀랍게도 잘 동작하고 있었습니다... import 안해도 잘 될거에요
- patch 와 delete 함수도 만들었습니다

2024-05-15 07:52 UTC, yeodahui commented on src/pages/mytrip/ViewAllPage/index.tsx
> +type travelResponseType = {
interface 대신 type 사용하시는 이유가 따로 있나여?

2024-05-15 07:58 UTC, SugarSyrup commented on src/pages/mytrip/ViewAllPage/index.tsx
> +type travelResponseType = {
어,,, 아무 생각없이 한듯요..? 저거는 interface 로 다 통일하는걸로 수정할게요

2024-05-15 08:03 UTC, yeodahui requested changes

2024-05-15 08:03 UTC, yeodahui commented on src/pages/mytrip/ViewAllPage/index.tsx
> +    const [tripData, setTripData] = useState<travelResponseType>([]);
2번은 이후 바꾸셨군용... 무시해주셔도 될 것 같습니다

2024-05-16 12:09 UTC, yeodahui approved these changes

2024-05-16 12:09 UTC, merged